name: Fetch Dashboard Resources

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 1 * * *'  # runs daily at 1AM UTC

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Set this in repo secrets!

      - name: Fetch dashboard files
        run: |
          mkdir -p website/
          curl -sSf https://pfwra.blob.core.windows.net/public/hexmap_2024.html -o website/hexmap_2024.html
          curl -sSf https://pfwra.blob.core.windows.net/public/bar_chart_2024.html -o website/bar_chart_2024.html
          curl -sSf https://pfwra.blob.core.windows.net/public/summary_stats.json -o website/summary_stats.json

      - name: Commit and push if there are changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add website/
            git commit -m "Update dashboard resources $(date --iso-8601=minutes)"
            git push
          else
            echo "No changes to commit."
          fi
