name: Fetch Dashboard Resources

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 1 * * *'  # runs daily at 1AM UTC

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # needed to push changes

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x ./fetch_resources.sh

      - name: Run fetch_resources.sh
        run: ./fetch_resources.sh
